<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('fee_transactions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('school_id')->constrained('schools')->cascadeOnDelete();
            $table->foreignId('ledger_id')->constrained('student_fee_ledgers')->cascadeOnDelete();

            $table->decimal('paid_amount', 10, 2);
            $table->date('payment_date');
            $table->string('payment_method')->nullable();
            $table->string('transaction_id')->nullable();

            // Human-friendly receipt reference; generated by app
            $table->string('receipt_no')->nullable();
            $table->text('note')->nullable();

            $table->timestamps();

            $table->index(['school_id', 'payment_date']);
            $table->index(['ledger_id', 'payment_date']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('fee_transactions');
    }
};

